from __future__ import annotations

import json
import os
from functools import lru_cache

import numpy as np
import pandas as pd


POSITIVE_TEMPLATES = {
    "rainfall": "rainfall conditions fit the variety adaptation range",
    "altitude": "the elevation is within the variety adaptation range",
    "maturity": "the maturity period fits the season length",
    "drought": "drought tolerance is useful for the local drought risk",
    "disease": "disease resistance strengthens suitability",
    "yield": "yield potential supports the farmer's production goal",
    "inputs": "input requirements match the farmer's resource level",
    "vegetation": "vegetation condition indicates a favourable growing environment",
}

CAUTION_TEMPLATES = {
    "rainfall": "rainfall is outside the preferred variety range",
    "altitude": "elevation is outside the preferred variety range",
    "maturity": "the variety may mature too late for the season length",
    "drought": "drought risk may challenge this variety",
    "disease": "disease resistance is relatively weak",
    "inputs": "the variety may require more inputs than the farmer can access",
    "availability": "seed availability is not confirmed locally",
}


def _fallback_explanation_sentence(row: pd.Series) -> str:
    drivers, cautions = agronomic_drivers(row)
    driver_text = "; ".join(drivers) if drivers else "available data gives moderate support for this variety"
    caution_text = "; ".join(cautions) if cautions else "no major caution was detected in the demo data"
    return f"Recommended because {driver_text}. Caution: {caution_text}."


def _row_signature(row: pd.Series, model_probability: float | None = None) -> tuple:
    fields = (
        "district",
        "season",
        "crop",
        "variety_name",
        "suitability_score",
        "suitability_class",
        "available",
        "data_confidence",
        "mean_rainfall_mm",
        "min_rainfall_mm",
        "max_rainfall_mm",
        "elevation_m",
        "min_altitude_m",
        "max_altitude_m",
        "maturity_days",
        "season_length_days",
        "drought_tolerance",
        "disease_resistance",
        "yield_potential_t_ha",
        "input_access",
        "input_requirement",
        "ndvi",
    )
    values = tuple(row.get(field) for field in fields)
    return values + (None if model_probability is None else float(model_probability),)


def _json_safe(value):
    if isinstance(value, np.generic):
        return value.item()
    if pd.isna(value):
        return None
    return value


def _gemini_model_candidates() -> list[str]:
    preferred = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    candidates = [preferred, "gemini-2.5-pro", "gemini-1.5-flash"]
    return [name for index, name in enumerate(candidates) if name and name not in candidates[:index]]


@lru_cache(maxsize=1024)
def _cached_gemini_explanation(signature: tuple, model_name: str) -> str | None:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return None

    try:
        from google import genai
    except Exception:
        return None

    client = genai.Client(api_key=api_key)
    fields = [
        "district",
        "season",
        "crop",
        "variety_name",
        "suitability_score",
        "suitability_class",
        "available",
        "data_confidence",
        "mean_rainfall_mm",
        "min_rainfall_mm",
        "max_rainfall_mm",
        "elevation_m",
        "min_altitude_m",
        "max_altitude_m",
        "maturity_days",
        "season_length_days",
        "drought_tolerance",
        "disease_resistance",
        "yield_potential_t_ha",
        "input_access",
        "input_requirement",
        "ndvi",
        "model_probability",
    ]
    row = dict(zip(fields, signature, strict=True))
    prompt = {
        "task": "Write a short agronomic explanation for a seed recommendation.",
        "tone": "clear, concise, non-technical, and honest about uncertainty",
        "rules": [
            "Use only the supplied row data.",
            "Do not mention that the text is generated by AI.",
            "Return 2 sentences maximum.",
            "First sentence should explain why the variety is suitable.",
            "Second sentence should mention any caution or availability issue if relevant.",
        ],
        "row": {
            key: _json_safe(value)
            for key, value in row.items()
        },
    }

    try:
        response = client.models.generate_content(
            model=model_name,
            contents=json.dumps(prompt, ensure_ascii=True),
        )
    except Exception:
        return None

    text = getattr(response, "text", None)
    if not text:
        return None
    return str(text).strip()


def gemini_explanation(row: pd.Series, model_probability: float | None = None) -> str | None:
    signature = _row_signature(row, model_probability)
    for model_name in _gemini_model_candidates():
        text = _cached_gemini_explanation(signature, model_name)
        if text:
            return text
    return None


def agronomic_drivers(row: pd.Series) -> tuple[list[str], list[str]]:
    drivers: list[str] = []
    cautions: list[str] = []

    if row["min_rainfall_mm"] <= row["mean_rainfall_mm"] <= row["max_rainfall_mm"]:
        drivers.append(POSITIVE_TEMPLATES["rainfall"])
    else:
        cautions.append(CAUTION_TEMPLATES["rainfall"])

    if row["min_altitude_m"] <= row["elevation_m"] <= row["max_altitude_m"]:
        drivers.append(POSITIVE_TEMPLATES["altitude"])
    else:
        cautions.append(CAUTION_TEMPLATES["altitude"])

    if row["maturity_days"] <= row["season_length_days"] + 15:
        drivers.append(POSITIVE_TEMPLATES["maturity"])
    else:
        cautions.append(CAUTION_TEMPLATES["maturity"])

    if row["drought_tolerance"] == "high" and row["drought_index"] >= 0.35:
        drivers.append(POSITIVE_TEMPLATES["drought"])
    elif row["drought_tolerance"] == "low" and row["drought_index"] >= 0.35:
        cautions.append(CAUTION_TEMPLATES["drought"])

    if row["disease_resistance"] == "high":
        drivers.append(POSITIVE_TEMPLATES["disease"])
    elif row["disease_resistance"] == "low":
        cautions.append(CAUTION_TEMPLATES["disease"])

    if row["yield_potential_t_ha"] >= 5 and row["production_goal"] in {"market", "food_and_market"}:
        drivers.append(POSITIVE_TEMPLATES["yield"])

    levels = {"low": 1, "medium": 2, "high": 3}
    if levels[row["input_access"]] >= levels[row["input_requirement"]]:
        drivers.append(POSITIVE_TEMPLATES["inputs"])
    else:
        cautions.append(CAUTION_TEMPLATES["inputs"])

    if row["ndvi"] >= 0.6:
        drivers.append(POSITIVE_TEMPLATES["vegetation"])

    if row["available"] != "yes":
        cautions.append(CAUTION_TEMPLATES["availability"])

    return drivers[:4], cautions[:3]


def explanation_sentence(row: pd.Series) -> str:
    gemini_text = gemini_explanation(row, row.get("model_probability"))
    if gemini_text:
        return gemini_text
    return _fallback_explanation_sentence(row)


def shap_summary(pipe, rows: pd.DataFrame) -> pd.DataFrame:
    try:
        import shap

        transformed = pipe.named_steps["preprocess"].transform(rows)
        model = pipe.named_steps["model"]
        explainer = shap.TreeExplainer(model)
        values = explainer.shap_values(transformed)
        if isinstance(values, list):
            values = values[-1]
        names = pipe.named_steps["preprocess"].get_feature_names_out()
        importance = np.abs(values).mean(axis=0)
        return pd.DataFrame({"feature": names, "mean_abs_shap": importance}).sort_values("mean_abs_shap", ascending=False)
    except Exception:
        return fallback_feature_importance(pipe)


def fallback_feature_importance(pipe) -> pd.DataFrame:
    model = pipe.named_steps["model"]
    names = pipe.named_steps["preprocess"].get_feature_names_out()
    if hasattr(model, "feature_importances_"):
        values = model.feature_importances_
    elif hasattr(model, "coef_"):
        values = np.abs(model.coef_[0])
    else:
        values = np.zeros(len(names))
    return pd.DataFrame({"feature": names, "importance": values}).sort_values("importance", ascending=False)

