from __future__ import annotations

import json
import os
from functools import lru_cache

import numpy as np
import pandas as pd
from pandas.api.types import is_numeric_dtype

from .config import RANDOM_SEED
from .data import feature_columns


POSITIVE_TEMPLATES = {
    "rainfall": "rainfall conditions fit the variety adaptation range",
    "altitude": "the elevation is within the variety adaptation range",
    "maturity": "the maturity period fits the season length",
    "drought": "drought tolerance is useful for the local drought risk",
    "disease": "disease resistance strengthens suitability",
    "yield": "yield potential supports the farmer's production goal",
    "inputs": "input requirements match the farmer's resource level",
    "vegetation": "vegetation condition indicates a favourable growing environment",
}

CAUTION_TEMPLATES = {
    "rainfall": "rainfall is outside the preferred variety range",
    "altitude": "elevation is outside the preferred variety range",
    "maturity": "the variety may mature too late for the season length",
    "drought": "drought risk may challenge this variety",
    "disease": "disease resistance is relatively weak",
    "inputs": "the variety may require more inputs than the farmer can access",
    "availability": "seed availability is not confirmed locally",
}


def _fallback_explanation_sentence(row: pd.Series) -> str:
    drivers, cautions = agronomic_drivers(row)
    driver_text = "; ".join(drivers) if drivers else "the available data gives moderate support for this variety"
    caution_text = "; ".join(cautions) if cautions else "no major concern was found for your conditions"
    return f"This variety suits your farm because {driver_text}. Things to watch: {caution_text}."


def _row_signature(row: pd.Series, model_probability: float | None = None) -> tuple:
    fields = (
        "district",
        "season",
        "crop",
        "variety_name",
        "suitability_score",
        "suitability_class",
        "available",
        "data_confidence",
        "mean_rainfall_mm",
        "min_rainfall_mm",
        "max_rainfall_mm",
        "elevation_m",
        "min_altitude_m",
        "max_altitude_m",
        "maturity_days",
        "season_length_days",
        "drought_tolerance",
        "disease_resistance",
        "yield_potential_t_ha",
        "input_access",
        "input_requirement",
        "ndvi",
    )
    values = tuple(row.get(field) for field in fields)
    return values + (None if model_probability is None else float(model_probability),)


def _json_safe(value):
    if isinstance(value, np.generic):
        return value.item()
    if pd.isna(value):
        return None
    return value


def _gemini_enabled() -> bool:
    """LLM text is opt-in so bulk pipeline/eval stay fast and offline by default."""
    return os.getenv("SEEDREC_USE_GEMINI", "").strip().lower() in {"1", "true", "yes", "on"}


def _gemini_model_candidates() -> list[str]:
    preferred = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    candidates = [preferred, "gemini-2.5-pro", "gemini-1.5-flash"]
    return [name for index, name in enumerate(candidates) if name and name not in candidates[:index]]


@lru_cache(maxsize=1024)
def _cached_gemini_explanation(signature: tuple, model_name: str) -> str | None:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return None

    try:
        from google import genai
    except Exception:
        return None

    client = genai.Client(api_key=api_key)
    fields = [
        "district",
        "season",
        "crop",
        "variety_name",
        "suitability_score",
        "suitability_class",
        "available",
        "data_confidence",
        "mean_rainfall_mm",
        "min_rainfall_mm",
        "max_rainfall_mm",
        "elevation_m",
        "min_altitude_m",
        "max_altitude_m",
        "maturity_days",
        "season_length_days",
        "drought_tolerance",
        "disease_resistance",
        "yield_potential_t_ha",
        "input_access",
        "input_requirement",
        "ndvi",
        "model_probability",
    ]
    row = dict(zip(fields, signature, strict=True))
    prompt = {
        "task": "Write a short agronomic explanation for a seed recommendation.",
        "tone": "clear, concise, non-technical, and honest about uncertainty",
        "rules": [
            "Use only the supplied row data.",
            "Do not mention that the text is generated by AI.",
            "Return 2 sentences maximum.",
            "First sentence should explain why the variety is suitable.",
            "Second sentence should mention any caution or availability issue if relevant.",
        ],
        "row": {
            key: _json_safe(value)
            for key, value in row.items()
        },
    }

    try:
        response = client.models.generate_content(
            model=model_name,
            contents=json.dumps(prompt, ensure_ascii=True),
        )
    except Exception:
        return None

    text = getattr(response, "text", None)
    if not text:
        return None
    return str(text).strip()


def gemini_explanation(row: pd.Series, model_probability: float | None = None) -> str | None:
    signature = _row_signature(row, model_probability)
    for model_name in _gemini_model_candidates():
        text = _cached_gemini_explanation(signature, model_name)
        if text:
            return text
    return None


def agronomic_drivers(row: pd.Series) -> tuple[list[str], list[str]]:
    drivers: list[str] = []
    cautions: list[str] = []

    if row["min_rainfall_mm"] <= row["mean_rainfall_mm"] <= row["max_rainfall_mm"]:
        drivers.append(POSITIVE_TEMPLATES["rainfall"])
    else:
        cautions.append(CAUTION_TEMPLATES["rainfall"])

    if row["min_altitude_m"] <= row["elevation_m"] <= row["max_altitude_m"]:
        drivers.append(POSITIVE_TEMPLATES["altitude"])
    else:
        cautions.append(CAUTION_TEMPLATES["altitude"])

    if row["maturity_days"] <= row["season_length_days"] + 15:
        drivers.append(POSITIVE_TEMPLATES["maturity"])
    else:
        cautions.append(CAUTION_TEMPLATES["maturity"])

    if row["drought_tolerance"] == "high" and row["drought_index"] >= 0.35:
        drivers.append(POSITIVE_TEMPLATES["drought"])
    elif row["drought_tolerance"] == "low" and row["drought_index"] >= 0.35:
        cautions.append(CAUTION_TEMPLATES["drought"])

    if row["disease_resistance"] == "high":
        drivers.append(POSITIVE_TEMPLATES["disease"])
    elif row["disease_resistance"] == "low":
        cautions.append(CAUTION_TEMPLATES["disease"])

    if row["yield_potential_t_ha"] >= 5 and row["production_goal"] in {"market", "food_and_market"}:
        drivers.append(POSITIVE_TEMPLATES["yield"])

    levels = {"low": 1, "medium": 2, "high": 3}
    if levels[row["input_access"]] >= levels[row["input_requirement"]]:
        drivers.append(POSITIVE_TEMPLATES["inputs"])
    else:
        cautions.append(CAUTION_TEMPLATES["inputs"])

    if row["ndvi"] >= 0.6:
        drivers.append(POSITIVE_TEMPLATES["vegetation"])

    if row["available"] != "yes":
        cautions.append(CAUTION_TEMPLATES["availability"])

    return drivers[:4], cautions[:3]


def explanation_sentence(row: pd.Series) -> str:
    if _gemini_enabled():
        gemini_text = gemini_explanation(row, row.get("model_probability"))
        if gemini_text:
            return gemini_text
    return _fallback_explanation_sentence(row)


def _pretty_feature(name: str) -> str:
    return str(name).split("__", 1)[-1].replace("_", " ").strip()


def _underlying_model(model):
    """Return the base tree estimator, unwrapping CalibratedClassifierCV if present."""
    if hasattr(model, "calibrated_classifiers_") and model.calibrated_classifiers_:
        calibrated = model.calibrated_classifiers_[0]
        return getattr(calibrated, "estimator", getattr(calibrated, "base_estimator", model))
    return model


def _positive_class_shap(values) -> np.ndarray:
    values = values[-1] if isinstance(values, list) else np.asarray(values)
    values = np.asarray(values)
    if values.ndim == 3:  # (samples, features, classes)
        values = values[..., -1]
    return values


def shap_summary(pipe, rows: pd.DataFrame) -> pd.DataFrame:
    try:
        import shap

        pre = pipe.named_steps["preprocess"]
        model = _underlying_model(pipe.named_steps["model"])
        transformed = pre.transform(rows)
        if hasattr(transformed, "toarray"):
            transformed = transformed.toarray()
        explainer = shap.TreeExplainer(model)
        values = _positive_class_shap(explainer.shap_values(transformed))
        names = pre.get_feature_names_out()
        importance = np.abs(values).mean(axis=0)
        return pd.DataFrame({"feature": names, "mean_abs_shap": importance}).sort_values("mean_abs_shap", ascending=False)
    except Exception:
        return fallback_feature_importance(pipe)


def local_shap_contributions(pipe, feature_rows: pd.DataFrame, top_n: int = 6):
    """Signed SHAP contributions for each row (technical explanation layer, sec. 2.6.3)."""
    try:
        import shap

        pre = pipe.named_steps["preprocess"]
        model = _underlying_model(pipe.named_steps["model"])
        transformed = pre.transform(feature_rows[feature_columns()])
        if hasattr(transformed, "toarray"):
            transformed = transformed.toarray()
        explainer = shap.TreeExplainer(model)
        values = _positive_class_shap(explainer.shap_values(transformed))
        names = [_pretty_feature(n) for n in pre.get_feature_names_out()]
        out = []
        for i in range(values.shape[0]):
            contrib = sorted(zip(names, values[i].tolist()), key=lambda t: abs(t[1]), reverse=True)
            out.append(contrib[:top_n])
        return out
    except Exception:
        return None


def save_shap_summary_figure(pipe, rows: pd.DataFrame, path) -> bool:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        summary = shap_summary(pipe, rows).head(15)
        col = "mean_abs_shap" if "mean_abs_shap" in summary.columns else "importance"
        labels = summary["feature"].map(_pretty_feature).tolist()[::-1]
        fig, ax = plt.subplots(figsize=(7.5, 5.5))
        ax.barh(labels, summary[col].tolist()[::-1], color="#2e7d32")
        ax.set_xlabel("Mean |SHAP| (global feature importance)")
        ax.set_title("What drives seed-variety suitability across all cases")
        fig.tight_layout()
        fig.savefig(path, dpi=120)
        plt.close(fig)
        return True
    except Exception:
        return False


def fallback_feature_importance(pipe) -> pd.DataFrame:
    model = _underlying_model(pipe.named_steps["model"])
    names = pipe.named_steps["preprocess"].get_feature_names_out()
    if hasattr(model, "feature_importances_"):
        values = model.feature_importances_
    elif hasattr(model, "coef_"):
        values = np.abs(model.coef_[0])
    else:
        values = np.zeros(len(names))
    return pd.DataFrame({"feature": names, "importance": values}).sort_values("importance", ascending=False)


# --- LIME local explanations (proposal sec. 2.6.2, 3.8.1) ---

_LIME_CACHE: dict = {}


def _lime_components(modelling_df: pd.DataFrame):
    feats = feature_columns()
    encoded = np.zeros((len(modelling_df), len(feats)), dtype=float)
    cat_flags = [False] * len(feats)
    cat_names: dict[int, list[str]] = {}
    for i, col in enumerate(feats):
        series = modelling_df[col]
        if is_numeric_dtype(series):
            numeric = pd.to_numeric(series, errors="coerce")
            median = numeric.median()
            fill = 0.0 if pd.isna(median) else median
            encoded[:, i] = numeric.fillna(fill).to_numpy(dtype=float)
        else:
            cats = series.astype(str).fillna("unknown")
            uniques = sorted(cats.unique())
            encoded[:, i] = cats.map({value: index for index, value in enumerate(uniques)}).to_numpy(dtype=float)
            cat_flags[i] = True
            cat_names[i] = uniques

    # LIME needs discretized perturbations to move a tree model off its locally-constant leaf.
    # Its quartile discretizer fails on constant or sparsely-populated numeric columns, so we
    # explain only well-spread features (and all categoricals); the rest are held at their
    # observed value as fixed context.
    usable = []
    for i in range(len(feats)):
        if cat_flags[i]:
            usable.append(i)
            continue
        column = encoded[:, i]
        if np.unique(column).size >= 10 and pd.Series(column).value_counts(normalize=True).iloc[0] < 0.6:
            usable.append(i)
    return feats, encoded, cat_flags, cat_names, usable


def _lime_explainer(modelling_df: pd.DataFrame):
    key = (tuple(feature_columns()), len(modelling_df))
    if key in _LIME_CACHE:
        return _LIME_CACHE[key]
    from lime.lime_tabular import LimeTabularExplainer

    feats, encoded, cat_flags, cat_names, usable = _lime_components(modelling_df)
    sub_feats = [feats[i] for i in usable]
    sub_cat_idx = [pos for pos, i in enumerate(usable) if cat_flags[i]]
    sub_cat_names = {pos: cat_names[usable[pos]] for pos in sub_cat_idx}
    explainer = LimeTabularExplainer(
        training_data=encoded[:, usable],
        feature_names=sub_feats,
        categorical_features=sub_cat_idx,
        categorical_names=sub_cat_names,
        class_names=["not suitable", "suitable"],
        mode="classification",
        discretize_continuous=True,
        random_state=RANDOM_SEED,
    )
    _LIME_CACHE[key] = (explainer, feats, cat_flags, cat_names, usable)
    return _LIME_CACHE[key]


def lime_explanation(pipe, modelling_df: pd.DataFrame, feature_row: pd.Series, num_features: int = 8):
    """Return [(reason, weight)] for one recommendation, or None if LIME is unavailable."""
    try:
        explainer, feats, cat_flags, cat_names, usable = _lime_explainer(modelling_df)

        full = np.zeros(len(feats), dtype=float)
        for i, col in enumerate(feats):
            value = feature_row.get(col)
            if cat_flags[i]:
                uniques = cat_names[i]
                text = str(value)
                full[i] = float(uniques.index(text)) if text in uniques else 0.0
            else:
                full[i] = float(value) if pd.notna(value) else 0.0

        def predict_fn(array: np.ndarray) -> np.ndarray:
            matrix = np.tile(full, (array.shape[0], 1))
            matrix[:, usable] = array
            frame = pd.DataFrame(matrix, columns=feats)
            for i in range(len(feats)):
                if cat_flags[i]:
                    uniques = cat_names[i]
                    idxs = np.clip(np.round(frame.iloc[:, i].to_numpy()).astype(int), 0, len(uniques) - 1)
                    frame[feats[i]] = [uniques[k] for k in idxs]
            return pipe.predict_proba(frame)

        explanation = explainer.explain_instance(full[usable], predict_fn, num_features=num_features, labels=(1,))
        items = [(_pretty_feature(text), float(weight)) for text, weight in explanation.as_list(label=1)]
        meaningful = [(text, weight) for text, weight in items if abs(weight) > 1e-6]
        return meaningful or items
    except Exception:
        return None


def technical_explanation(pipe, modelling_df: pd.DataFrame, case_id, variety_id, with_lime: bool = False) -> dict:
    """SHAP (and optionally LIME) contributions for one recommended variety."""
    match = modelling_df[(modelling_df["case_id"].eq(case_id)) & (modelling_df["variety_id"].eq(variety_id))]
    if match.empty:
        return {"shap": None, "lime": None}
    feature_row = match.iloc[[0]]
    shap_local = local_shap_contributions(pipe, feature_row, top_n=6)
    result = {"shap": shap_local[0] if shap_local else None, "lime": None}
    if with_lime:
        result["lime"] = lime_explanation(pipe, modelling_df, feature_row.iloc[0])
    return result

